default['redis']['bind']         = "127.0.0.1"
default['redis']['port']         = "6379"
default['redis']['config_path']  = "/etc/redis/redis.conf"
default['redis']['daemonize']    = "yes"
default['redis']['timeout']      = "300"
default['redis']['loglevel']     = "notice"
